site_name: Notes
site_url: https://tanwlanyue.github.io/notes/
site_author: tanwlanyue
repo_name: tanwlanyue/notes
repo_url: https://github.com/tanwlanyue/notes
extra_css:
  - stylesheets/extra.css
theme:
  name: material
  logo: assets/note.svg
  favicon: assets/pkmgo.jpeg
  palette:
    - media: "(prefers-color-scheme: light)"
      primary: blue
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: black
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  icon:
    repo: fontawesome/brands/git-alt
    edit: material/pencil 
    view: material/eye
  features:
    - navigation.instant
    - content.action.edit
    - content.action.view
    - content.code.copy
    - content.code.annotate
  language: zh
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
plugins:
  - glightbox
  - search